baseURL = "https://cv.arlyon.co/"
languageCode = "en-us"
title = "Alexander Lyon's CV"
theme = "CAPSLOCK"
disableKinds = ["sitemap"]

googleAnalytics = "UA-55373202-4"
enableRobotsTXT = true
enableGitInfo = true
sectionPagesMenu = "main"
pygmentsOptions = "linenos=inline"
pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true

# custom settings

[params]
    author = "Alexander Lyon"
    description = "A resume."
    foreground = "#000"
    service_worker = false

[params.cv]
    enabled = true
    sections = ["projects", "employment", "education", "responsibilities"]

[params.cv.data]
    location = "Edinburgh"
    site = "https://blog.arlyon.co"
    email = "arlyon@me.com"
    github = "arlyon"
    gitlab = "git.arlyon.co"
    currently = "Comp.Eng @ Heriot Watt"
    blurb = "A tech and open source enthusiast."

# misc data

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true