baseURL = "https://cv.arlyon.dev/"
languageCode = "en-us"
title = "Alexander Lyon's CV"
theme = "CAPSLOCK"
disableKinds = ["sitemap"]

googleAnalytics = "UA-55373202-4"
enableRobotsTXT = true
enableGitInfo = true
sectionPagesMenu = "main"
pygmentsOptions = "linenos=inline"
pygmentsStyle = "bw"
pygmentsUseClasses = true
pygmentsCodeFences = true

[taxonomies]
    skill = "skills"

# custom settings

[params]
    author = "Alexander Lyon"
    description = "A tech, privacy, and open source enthusiast based in Edinburgh, Scotland"
    foreground = "#000"
    service_worker = false

[params.cv]
    enabled = true
    sections = ["projects", "employment", "education", "responsibilities"]
    min_for_tag = 3

[params.cv.data]
    location = "Edinburgh"
    site = "https://blog.arlyon.dev"
    email = "arlyon@me.com"
    phone = "07434848282"
    github = "arlyon"
    gitlab = "git.arlyon.co"
    currently = "Soft.Eng. @ [Codethink](https://codethink.co.uk)"

# misc data

[outputs]
    home = [ "HTML", "RSS", "HEADERS" ]
    page = [ "HTML" ]

[mediaTypes]
    [mediaTypes."text/netlify"]
    suffixes = [""]
    delimiter = ""

[outputFormats]
    [outputFormats.HEADERS]
    mediatype = "text/netlify"
    baseName = "_headers"
    isPlainText = true
    notAlternative = true
